react/package-lock.json
react/package.json

Updates npm package number for npm versioning

Update version number for npm publish

---

react/package-lock.json
react/package.json

Update npm package version for publish event

---

react/package-lock.json
react/package.json

Fix security issue with glob-parent of storybook-core.

MAT-4065d: Add npm override for nested glob-parent dependency.

---

react/components/Footer/FooterUI.jsx
react/components/Footer/LegacyFooterUI.jsx

This is an update to change some of the text to from QPP to MADiE and add a few links so they do not break.

change qpp to MADiE in Footer

---

react/components/MadieDialog/Index.jsx
react/components/Toast/index.jsx
react/components/index.js
react/package-lock.json
react/package.json
react/test/components/MadieDialog.test.js
react/test/components/MadieSpinner.test.js
react/test/components/Toast.test.js

This PR adds reusable dialog for both form and display elements to support the requirements of MAT-4415.

Release 1.0.12

---

.github/workflows/npm-publish.yml
.github/workflows/unit_test_coverage.yml

Jira Ticket: [MAT-4415](https://jira.cms.gov/browse/MAT-4415)
This PR updates the yml file for automatic releases to correctly look for working directory

Release 1.0.13

---

.github/workflows/npm-publish.yml

This PR adds a work space other than the default workspace specified at the job level to pass to the publish script since it checks that instead.
Jira Ticket: [MAT-4415](https://jira.cms.gov/browse/MAT-4415)

Release 1.0.13 yml fix 2

---

react/components/ReadOnlyTextField/ReadOnlyTextField.stories.js
react/components/ReadOnlyTextField/index.jsx
react/components/index.js
react/test/components/ReadOnlyTextField.test.js

Jira Ticket: [MAT-4569](https://jira.cms.gov/browse/MAT-4569)
Creates a component for read only text fields

Release 1.0.16

---

react/components/Footer/FooterUI.jsx
react/package-lock.json
react/package.json

Jira Ticket: [MAT-4921](https://jira.cms.gov/browse/MAT-4921)

Mat 4921 alt text 508

---

react/components/MadieDialog/index.jsx
react/package-lock.json
react/package.json

Jira Ticket: [MAT-4925](https://jira.cms.gov/browse/MAT-4925)

Mat 4925 508 compliance

---

react/components/MadieDialog/index.jsx
react/components/Pagination/Pagination.stories.js
react/components/Pagination/index.jsx
react/package-lock.json
react/package.json

Jira Ticket: [MAT-4923](https://jira.cms.gov/browse/MAT-4923)
[MAT-4931](https://jira.cms.gov/browse/MAT-4931) 508: Discard Changes Modal

MAT-4923 508 & MAT-4931- accessibility enhancements

---

react/package-lock.json
react/package.json
shared/styles/qppds/components/_link.scss
shared/styles/qppds/settings/variables/_color.scss

Jira Ticket: [MAT-4668](https://jira.cms.gov/browse/MAT-4668)

MAT-4669 global link color

---

react/package-lock.json
react/package.json
shared/styles/qppds/components/_link.scss
shared/styles/qppds/settings/variables/_color.scss

Jira Ticket: [MAT-4668](https://jira.cms.gov/browse/MAT-4668)

revert previous change for new requirement

---

react/components/MadieDeleteDialog/MadieDeleteDialog.stories.js
react/components/MadieDeleteDialog/index.jsx
react/components/index.js
react/package-lock.json
react/package.json
react/test/components/MadieDeleteDialog.test.js
shared/styles/_qpp-style.scss
shared/styles/components/_madie-delete-dialog.scss
shared/styles/qppds/components/_madie-delete-dialog.scss
shared/styles/qppds/components/index.scss

Jira Ticket: [MAT-5001](https://jira.cms.gov/browse/MAT-5001)
Added modal for deleting

Added delete dialog Modal

---

react/package-lock.json

Updated package lock

---

react/components/Pagination/index.jsx
react/package-lock.json
react/package.json

Jira Ticket: [MAT-4923](https://jira.cms.gov/browse/MAT-4923)

MAT-4923 508: Link Items Per Page Drop Down With Label

---

react/components/Pagination/index.jsx
react/package-lock.json
react/package.json

Jira Ticket: [MAT-4923](https://jira.cms.gov/browse/MAT-4923)

MAT4923 508: Link Items Per Page Drop Down With Label

---

react/components/Pagination/index.jsx
react/components/Popover/Popover.stories.js
react/components/Popover/index.js
react/components/index.js
react/package-lock.json
react/package.json
react/test/components/MadiePopover.test.js

Jira Ticket: [MAT-5021](https://jira.cms.gov/browse/MAT-5021)
added popover

added popover

---

react/components/Toast/Toast.stories.js
react/components/Toast/index.jsx
react/package-lock.json
react/package.json
react/test/components/Toast.test.js
shared/styles/_qpp-style.scss
shared/styles/components/_toast.scss
shared/styles/qppds/components/_toast.scss
shared/styles/qppds/components/index.scss

Jira Ticket: [MAT-4878](https://jira.cms.gov/browse/MAT-4878)
Adds to the Toast component to create more consistent alerts across Madie.
Example Toast:

MAT-4878: MadieToast component

---

react/components/AutoComplete/AutoComplete.jsx
react/components/Select/index.jsx
react/components/TextField/index.jsx
react/package-lock.json
react/package.json

Jira Ticket: [MAT-5111](https://jira.cms.gov/browse/MAT-5111)

Make placeholder and text inputs complant for contrast

---

react/components/TextField/index.jsx
react/package-lock.json
react/package.json

Jira Ticket: [MAT-5110](https://jira.cms.gov/browse/MAT-5110)
Add a remove opacity check, bump version

Mat-5110 revision

---

react/components/AutoComplete/AutoComplete.jsx
react/components/AutoComplete/AutoComplete.stories.js
react/components/Select/Select.stories.js
react/components/Select/index.jsx
react/components/TextField/TextField.stories.js
react/components/TextField/index.jsx
react/package-lock.json
react/package.json

Jira Ticket: [MAT-5180](https://jira.cms.gov/browse/MAT-5180)
Update design system components for Select, Textfield, AutoComplete, add stories, make responsive

Update design system for 508 compliance: Mat-5180

---

react/package-lock.json
react/package.json

Not associated with specific ticket number.
This pr is required to prevent blocking changes. This PR
Removes an unused dependency that causes issue with subscribed applications.
Updates design-system to a version that doesn't conflict with old versions to prevent issues with --legacy peer dependencies.
*  If you have any concerns they are brought up either to the …

Update dependencies to unblock subscribed applications from merging PRs

---

react/components/Tabs/Tab.js
react/components/Tabs/Tabs.stories.js
react/components/Tabs/index.js
react/package-lock.json
react/package.json
react/test/components/Tabs.test.js
react/test/components/TextArea.test.js

Jira Ticket: [MAT-5326](https://jira.cms.gov/browse/MAT-5326)

MAT-5326: Implement 4 types of reusable navigations

---

react/components/index.js
react/package-lock.json
react/package.json

Jira Ticket: [MAT-5326](https://jira.cms.gov/browse/MAT-5326)

MAT-5326: Commit missing tab export

---

react/components/Tabs/Tab.js
react/components/Tabs/Tabs.stories.js
react/components/Tabs/index.js
react/package-lock.json
react/package.json
react/test/components/Tabs.test.js

Jira Ticket: [MAT-5326](https://jira.cms.gov/browse/MAT-5326)
Minor changes based on feedback

MAT-5326: Update Tabs from feedback. bump version

---

react/components/RadioButton/RadioButton.jsx
react/components/RadioButton/RadioButton.stories.jsx
react/components/index.js
react/package-lock.json
react/package.json

Jira Ticket: [MAT-5536](https://jira.cms.gov/browse/MAT-5536)

Added new reusable radio button component

---

react/package-lock.json
react/package.json

Jira Ticket: [MAT-5729](https://jira.cms.gov/browse/MAT-5729)
update version number

Mat 5729/date field component

---

react/components/DateField/DateField.jsx
react/components/DateField/DateField.stories.jsx
react/components/DateTimeField/DateTimeField.jsx
react/components/DateTimeField/DateTimeField.stories.jsx
react/package.json
react/test/components/DateField.test.js
react/test/components/DateTimeField.test.js

Jira Ticket: [MAT-5727](https://jira.cms.gov/browse/MAT-5727)
fixing can edit for date and datetime field

fixed can edit

---

react/components/TimeField/TimeField.js
react/components/TimeField/TimeField.stories.js
react/package-lock.json
react/package.json

Jira Ticket: [MAT-5828](https://jira.cms.gov/browse/MAT-5828)

MAT-5828 time field

---

react/components/Popover/index.js
react/package-lock.json
react/package.json

Jira Ticket: [MAT-6203](https://jira.cms.gov/browse/MAT-6203)
updating popover properties

Mat 6203/updating popover properties

---

react/components/DateTimeField/DateTimeField.jsx

Jira Ticket: [MAT-6185](https://jira.cms.gov/browse/MAT-6185)
This PR adds a reference to the utc plugin that needs be declared in the scope of the date adapter. This pr tells adapter that it's utc.

MAT-6185: update dateTimeField component to use utc adapter.

---

react/package-lock.json
react/package.json

Jira Ticket: [MAT-6185](https://jira.cms.gov/browse/MAT-6185)

bump package version

---

react/.storybook/preview.js
react/components/DateField/DateField.jsx
react/package-lock.json
react/package.json

Jira Ticket: [MAT-6311](https://jira.cms.gov/browse/MAT-6311)
fixing date bug

fixing date bug

---

react/components/DateField/DateField.jsx
react/package-lock.json
react/package.json

Jira Ticket: [MAT-6311](https://jira.cms.gov/browse/MAT-6311)
fix date bug

Mat 6311/fix date bug

---

react/components/DateField/DateField.jsx
react/components/DateTimeField/DateTimeField.jsx
react/components/Search/index.js
react/components/Select/index.jsx
react/components/TextArea/index.jsx
react/components/TextField/index.jsx
react/components/TimeField/TimeField.jsx
react/package-lock.json
react/package.json
react/styles/qppds/components/_button.scss

Jira Ticket: [MAT-0000](https://jira.cms.gov/browse/MAT-6431)

MAT-6431: update for 508 compliance

---

react/components/AutoComplete/AutoComplete.jsx
react/package-lock.json
react/package.json

Jira Ticket: [MAT-6431](https://jira.cms.gov/browse/MAT-6431)

MAT-6431, fix compliance issues with autocomplete, bump version.

---

react/components/AutoComplete/AutoComplete.jsx
react/package-lock.json
react/package.json

Jira Ticket: [MAT-6431](https://jira.cms.gov/browse/MAT-6431)

MAT-6431: Update chip styling to happen as a styleRule instead of a chip prop.

---

react/components/MadieDialog/index.jsx
react/components/Pagination/index.jsx
react/components/Popover/index.js
react/package-lock.json
react/package.json
react/styles/qppds/components/_button.scss

Jira Ticket: [MAT-6431](https://jira.cms.gov/browse/MAT-6431)

MAT-6431: Fix compliance issues with dividers and borders. bump version.

---

react/components/InputLabel/index.jsx
react/components/ReadOnlyTextField/index.jsx
react/components/TextField/TextField.stories.js
react/package-lock.json
react/package.json

Jira Ticket: [MAT-6431](https://jira.cms.gov/browse/MAT-6431)

MAT-6431:  fix readOnly textfield

---

react/components/MadieDialog/MadieDialog.stories.js
react/components/MadieDialog/index.jsx
react/components/ReadOnlyTextField/index.jsx
react/components/TextField/index.jsx
react/package-lock.json
react/package.json

Jira Ticket: [MAT-6488](https://jira.cms.gov/browse/MAT-6488)

MAT-6488: Add required prop to add a required indicator on dialogs

---

react/components/TextArea/index.jsx
react/package-lock.json
react/package.json

Jira Ticket: [MAT-6740](https://jira.cms.gov/browse/MAT-6740)

MAT-6740 set max width on dynamic text fields

---

.github/workflows/npm-publish.yml

This is a follow up PR because after merging the main fix, I discovered the npm-publish isn't working

Release 1.2.10

---

.github/workflows/npm-publish.yml

Mat 6432 fixing broken packagelock

---

react/package.json

Release 1.2.12 Mat 6432 fixing broken packagelock

---

react/package.json

Jira Ticket: [MAT-6432://jira.cms.gov/browse/MAT-6432)

MAT-6432: Release 1.2.14 still trying to fix deploy

---

react/components/ReadOnlyTextField/index.jsx
react/components/TextField/index.jsx
react/package-lock.json
react/package.json

Jira Ticket: [MAT-6864](https://jira.cms.gov/browse/MAT-6864)

Release 1.2.15 - Multiselect Checkbox Can Grow

---

.github/workflows/npm-publish.yml
react/components/DateField/DateField.jsx
react/package-lock.json
react/package.json

MAT-6432: Bumping x-date-pickers version to match madie-measure

---

.github/workflows/npm-publish.yml

MAT-6432: Bumping to vesrion 1.2.15 ..npm publish

---

react/package.json

Mat 6432 fixing date picker version

---

.github/workflows/npm-publish.yml
react/package.json

MAT-6432: Bumping to vesrion 1.2.17

---

react/package.json

MAT-6432: Bumping to vesrion 1.2.16-tempb trying to fix npm_publish

---

.github/workflows/npm-publish.yml
react/package-lock.json
react/package.json

Trying to fix the npm_publish task

Release 0.21

---

.github/workflows/npm-publish.yml

Release 1.2.17-beta.0

---

.github/workflows/unit_test_coverage.yml
react/components/NumberInput/NumberInput.stories.js
react/components/NumberInput/index.jsx
react/components/index.js
react/package-lock.json
react/package.json

Jira Ticket: [MAT-7151](https://jira.cms.gov/browse/MAT-7151)
1. A new Integer specific Input component.

Release 1.2.19 - MAT-7151 Number Input Component

---

react/components/NumberInput/index.jsx
react/package-lock.json
react/package.json

1. Allowing hypen (-) instead preventing decimal values

Release 1.2.20 MAT-7151 Updated Number TextField to allow hypen(-) for negative numbers

---

react/components/MadieTooltip/index.jsx

Jira Ticket: [MAT-7335](https://jira.cms.gov/browse/MAT-7335)

MAT-7335: preventdefault tooltip onclick

---

react/package-lock.json
react/package.json

Jira Ticket: [MAT-6393](https://jira.cms.gov/browse/MAT-6393)

Release 1.2.21

---

react/package-lock.json
react/package.json
react/styles/components/_madie-tooltip.scss

Release 1.2.22

---

react/package-lock.json
react/package.json
react/styles/qppds/components/_madie-tooltip.scss

Hat to update styling for tooltop in qppds as these styles are overriding the styles from styles directory

Release 1.2.23

---

react/package-lock.json
react/package.json

Jira Ticket: [MAT-7462](https://jira.cms.gov/browse/MAT-7462)
- axios vulnerability fix
-

Release 1.2.24

---

react/package-lock.json
react/package.json

Jira Ticket: [MAT-6188](https://jira.cms.gov/browse/MAT-6188)

MAT-6188: version bump

---

Dockerfile

Jira Ticket: [MAT-7594](https://jira.cms.gov/browse/MAT-7594)

MAT-7594 update docker file

---

react/components/MadieAlert/index.jsx
react/package-lock.json
react/package.json
react/test/components/MadieAlert.test.js

Jira Ticket: [MAT-6188](https://jira.cms.gov/browse/MAT-6188)

Trigger Release 1.2.27

---

react/components/MadieAlert/index.jsx
react/package-lock.json
react/package.json
react/test/components/MadieAlert.test.js

Jira Ticket: [MAT-6188](https://jira.cms.gov/browse/MAT-6188)

MAT-6188: fix newlines

---

Dockerfile
react/package-lock.json
react/package.json

Not associated with a ticket number .
Removing docker file that doesn't do anything since it's an npm package. 
This is also triggering multiple security issues by existing. 

Release 1.2.29

---

react/package-lock.json
react/package.json

Jira Ticket: [MAT-7639](https://jira.cms.gov/browse/MAT-7639)
Release updates to DateTimeField.

Release 1.2.30

---

react/components/DateField/DateField.jsx
react/package-lock.json
react/package.json
react/test/components/DateField.test.js

Jira Ticket: [MAT-7677](https://jira.cms.gov/browse/MAT-7677)

Release 1.2.33

---

react/components/TimeField/TimeField.jsx
react/package-lock.json
react/package.json

Jira Ticket: [MAT-7679](https://jira.cms.gov/browse/MAT-7679)

Release 1.2.34

---

react/components/TextField/TextField.stories.js
react/components/TextField/index.jsx
react/package-lock.json
react/package.json
react/test/components/TextField.test.js

Jira Ticket: [MAT-7672](https://jira.cms.gov/browse/MAT-7672)

Release 1.2.35

---

react/package-lock.json
react/package.json

Jira Ticket: [MAT-7672](https://jira.cms.gov/browse/MAT-7672)

Release 1.2.36

---

react/.storybook/main.js
react/components/DateTimeField/DateTimeField.jsx
react/components/Instant/Instant.stories.js
react/components/Instant/index.jsx
react/components/MadieDialog/MadieDialog.stories.js
react/components/MadieDialog/index.jsx
react/components/TextField/TextField.stories.js
react/components/TextField/index.jsx
react/components/index.js
react/package-lock.json
react/package.json
react/test/components/Instant.test.js
react/webpack.config.react.js

Jira Ticket: [MAT-7677](https://jira.cms.gov/browse/MAT-7677)

Release 1.2.37

---

.github/workflows/npm-publish.yml
.github/workflows/unit_test_coverage.yml
react/package-lock.json

Jira Ticket: [MAT-7896](https://jira.cms.gov/browse/MAT-7896)

MAT-7896 update github actions to v4

---

react/components/MadieConfirmDialog/MadieConfirmDialog.stories.js
react/components/MadieConfirmDialog/index.jsx
react/package-lock.json
react/package.json
react/styles/_qpp-style.scss
react/styles/components/_madie-confirm-dialog.scss
react/styles/qppds/components/_madie-confirm-dialog.scss
react/styles/qppds/components/index.scss
react/test/components/MadieConfirmDialog.test.js

Jira Ticket: [MAT-4169](https://jira.cms.gov/browse/MAT-4169)

Release 1.2.38

---

react/components/index.js
react/package-lock.json
react/package.json

Release 1.2.39

---

.github/workflows/npm-publish.yml
react/package-lock.json
react/package.json

Release 1.2.41

---

react/components/Tabs/Tab.js

Jira Ticket: [MAT-8171](https://jira.cms.gov/browse/MAT-8171)
https://github.com/MeasureAuthoringTool/madie-layout/pull/387
https://github.com/MeasureAuthoringTool/madie-measure/pull/765

MAT-8171: Fix padding and spacing on Measure screen

---

react/components/AutoComplete/AutoComplete.jsx
react/package-lock.json
react/package.json

Jira Ticket: [MAT-8274](https://jira.cms.gov/browse/MAT-8274)

Release 1.2.44

---

react/components/MadieDialog/MadieDialog.stories.js
react/components/MadieDialog/index.jsx
react/package-lock.json
react/package.json

Jira Ticket: [MAT-8164](https://jira.cms.gov/browse/MAT-8164)
Example 👍 

Release 1.2.45

---

react/components/Popover/index.js
react/package-lock.json
react/package.json

Release 1.2.46

---

react/components/TextField/index.jsx
react/package-lock.json
react/package.json
react/test/components/TextField.test.js

Jira Ticket: [MAT-8332](https://jira.cms.gov/browse/MAT-8332)

Release 1.2.47

---

react/components/TextArea/index.jsx
react/package-lock.json
react/package.json
react/test/components/TextArea.test.js

Jira Ticket: [MAT-8332](https://jira.cms.gov/browse/MAT-8332)

Release 1.2.48

---

react/components/TextArea/index.jsx
react/components/TextField/index.jsx
react/package-lock.json
react/package.json

Jira Ticket: [MAT-8332](https://jira.cms.gov/browse/MAT-8332)

Release 1.2.49

---

react/components/Tabs/Tab.js
react/package.json

Jira Ticket: [MAT-8477](https://jira.cms.gov/browse/MAT-8477)

MAT-8477: Changed font style to use teh color

---

react/components/index.js
react/package-lock.json
react/package.json
react/themes/actionCenterTheme.js

Jira Ticket: [MAT-8595](https://jira.cms.gov/browse/MAT-8595)

Release 1.2.51 - adding a custom theme for MADiE apps

---

react/components/MadieDialog/MadieDialog.stories.js
react/components/MadieDialog/index.jsx
react/package-lock.json
react/package.json
react/test/components/MadieDialog.test.js

Jira Ticket: [MAT-8569](https://jira.cms.gov/browse/MAT-8569)

Release 1.2.52

---

react/components/MadieDialog/MadieDialog.stories.js
react/components/MadieDialog/index.jsx
react/package-lock.json
react/package.json
react/test/components/MadieDialog.test.js

Jira Ticket: [MAT-8383](https://jira.cms.gov/browse/MAT-8383)

Release 1.2.53

---

react/components/MadieAlert/index.jsx
react/package-lock.json
react/package.json
react/test/components/MadieAlert.test.js

Jira Ticket: [MAT-8414](https://jira.cms.gov/browse/MAT-8414)

MAT-8414: add minimize button to MadieAlert

---

react/components/MadieDeleteDialog/MadieDeleteDialog.stories.js
react/components/MadieDeleteDialog/index.jsx
react/package-lock.json
react/package.json
react/test/components/MadieDeleteDialog.test.js

Jira Ticket: [MAT-8530](https://jira.cms.gov/browse/MAT-8530)

Release 1.2.56

---

README.md
react/components/AutoComplete/AutoComplete.jsx
react/components/MadieAlert/index.jsx
react/components/Tabs/Tabs.stories.js
react/components/Tabs/index.js
react/components/Tabs/tabs.scss
react/components/TextArea/index.jsx
react/components/TextField/index.jsx
react/package-lock.json
react/package.json
react/styles/components/_madie-alert.scss
react/styles/qppds/components/_rich-text-editor.scss
react/test/components/MadieAlert.test.js

Jira Ticket: [MAT-8637](https://jira.cms.gov/browse/MAT-8637)

Release 1.2.58

---

react/components/AutoComplete/AutoComplete.jsx
react/components/DateField/DateField.jsx
react/components/DateField/DateField.stories.jsx
react/components/DateTimeField/DateTimeField.jsx
react/components/DateTimeField/DateTimeField.stories.jsx
react/components/RadioButton/RadioButton.jsx
react/components/RadioButton/RadioButton.stories.jsx
react/components/ReadOnlyTextField/ReadOnlyTextField.stories.js
react/components/ReadOnlyTextField/index.jsx
react/components/Select/index.jsx
react/components/TextArea/TextArea.stories.js
react/components/TextArea/index.jsx
react/components/TextField/index.jsx
react/package-lock.json
react/package.json
react/test/components/AutoComplete.test.js
react/test/components/DateField.test.js
react/test/components/DateTimeField.test.js
react/test/components/RadioButton.test.js
react/test/components/ReadOnlyTextField.test.js
react/test/components/Select.test.js
react/test/components/TextArea.test.js
react/test/components/TextField.test.js

MAT-5679 change UI for readonly/disabled fields
Jira Ticket: [MAT-5679](https://jira.cms.gov/browse/MAT-5679)

Release 1.2.61

---

.github/workflows/npm-publish.yml
react/package-lock.json
react/package.json

Jira Ticket: [MAT-8816](https://jira.cms.gov/browse/MAT-8816)

Release v1.2.63

---

README.md
react/components/RichTextEditor/index.jsx
react/package-lock.json
react/package.json
react/test/components/RichTextEditor.test.js

Jira Ticket: [MAT-8671](https://jira.cms.gov/browse/MAT-8671)

Release MAT-8671 update default strikethrough tag. flexmark expects it to be <del> instead of <s>

---

react/components/RichTextEditor/RichTextEditor.stories.js
react/components/RichTextEditor/index.jsx
react/package-lock.json
react/package.json
react/styles/components/_rich-text-editor.scss
react/styles/qppds/components/_rich-text-editor.scss
react/test/components/RichTextEditor.test.js

Jira Ticket: [MAT-8828](https://jira.cms.gov/browse/MAT-8828)

Release 1.2.70 - MAT:8828: fix formatting in read only rte

---

react/components/RichTextEditor/index.jsx
react/package-lock.json
react/package.json

Jira Ticket: [MAT-9017](https://jira.cms.gov/browse/MAT-9017)

Release MAT-9017 skip editor initialization for readonly state

---

react/components/RichTextEditor/index.jsx
react/package-lock.json
react/package.json
react/test/components/RichTextEditor.test.js

Jira Ticket: [MAT-9031](https://jira.cms.gov/browse/MAT-9031)

Release MAT-9031 add missing label and css for readonly text editor

---

react/components/MadieDeleteDialog/MadieDeleteDialog.stories.js
react/components/MadieDeleteDialog/index.jsx
react/package-lock.json
react/package.json
react/test/components/MadieDeleteDialog.test.js

Jira Ticket: [MAT-9046](https://jira.cms.gov/browse/MAT-9046)

Release 1.2.75
